### PR TITLE
component/playground: rm the restriction that tikv num must be greater than 0

### PR DESCRIPTION
**Pull request by lilinghai**
Signed-off-by: lilinghai <lilinghai@pingcap.com>

### What problem does this PR solve? 

In order to construct a pd with monitor quickly in pd test, we remove the restriction thas tikv num must be greater than 0.
### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by nexustar** [comment]
please modify the error message together

**Comment by lilinghai** [comment]
> please modify the error message together

done

**Comment by nexustar** [comment]
please sign the CLA

**Review by nexustar — APPROVED** [review]

**Pull request merged**
