### PR TITLE
tiup: fix -v/--version argument

### PR DESCRIPTION
**Pull request by AstroProfundis**
### What problem does this PR solve? 
Not able to show components' version as the `-v/--version` was always been processed by `tiup`. It was introduced in #1158 

### What is changed and how it works?
Not using cobra's builtin `Version` field, but define a custom version argument in `tiup`.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by 9547** [comment]
Another question that's a little bit related, when I'm running `tiup dm -v`, the output doesn't show dm, does it by design or not:

image

**Comment by AstroProfundis** [comment]
> does it by design or not

That's not totally by design, but is the expected behaviour. The field is actually the `args[0]` of the command, if you invoke the `tiup-dm` binary directly you'll see the difference.

We have some tricks handling `args[0]` in `cluster` to show correctly help messages, but they're generally not essential so it could be ok to just leave them alone.

**Pull request merged**
