### PR TITLE
Update topology.example.yaml

### PR DESCRIPTION
**Pull request by 2983777417**
### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Review by lucklove — APPROVED** [review]
LGTM, thanks for your contribute.

**Comment by lucklove** [comment]
Hi~ @2983777417 Can you sign the [Contributor License Agreement](https://cla-assistant.io/pingcap/tiup?pullRequest=914)?

**Comment by glkappe** [comment]
I'm very sorry @2983777417 , this pr is important to me, I will fix it through https://github.com/pingcap/tiup/pull/1155, please conduct a technical review
@lucklove

**Pull request closed without merging**
