### PR TITLE
Refine cluster list and display commands

### PR DESCRIPTION
**Pull request by baurine**
### What problem does this PR solve? 

In related PR #706 (tiup cluster UI), I need interfaces to get the cluster list and instances of a cluster.

I have implemented it in #706 , but I often need to handle conflicts when the master changes the related code, so I decide to cherry-pick this part of the code to the master.

### What is changed and how it works?

- Extract GetClusterList() method from ListCluster() method
- Extract GetClusterTopology() method from Display() method

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

 - Has exported function/method change
 - Has exported variable/fields change

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by baurine** [comment]
@lucklove please help take a look, thanks!

**Comment by AstroProfundis** [comment]
Could you post a screenshot of what the output of `display` command is like now? I believe it didn't change the console output?

Also, did you tested with `dm` component? The manager part is shared by `dm` and `cluster` AFAIK.

**Comment by baurine** [comment]
> Could you post a screenshot of what the output of `display` command is like now? I believe it didn't change the console output?
> 
> Also, did you tested with `dm` component? The manager part is shared by `dm` and `cluster` AFAIK.

Sure, I did the test manually, and the outputs are exactly the same.

image

image

**Comment by baurine** [comment]
How do I test with `dm` component? I never used `dm` before.

**Comment by AstroProfundis** [comment]
`dm` should work much like `cluster`, only that it deploys a DM cluster.

**Comment by baurine** [comment]
Manaully test result for `tiup dm`:

WeCom20210219-163906@2x

WeCom20210219-164004@2x

WeCom20210219-164140@2x

WeCom20210219-164208@2x

**Review by AstroProfundis — APPROVED** [review]

**Pull request merged**
