### PR TITLE
upgrade go-sql-driver/mysql version to v1.7.1

### LINKED ISSUE #2237: Upgrade go-sql-driver/mysql version to v1.7.1
## Feature Request

**Is your feature request related to a problem? Please describe:**

https://asktug.com/t/topic/1010860

**Describe the feature you'd like:**

upgrade github.com/go-sql-driver/mysql version to v1.7.1
silmilar like https://github.com/pingcap/tidb/pull/43507

**Why the featue is needed:**

current version: github.com/go-sql-driver/mysql v1.6.0

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by srstack**
### What problem does this PR solve? 

close #2237 

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by dveeden** [comment]
unit-test reports: "Files go.sum and /tmp/go.sum.before differ". Maybe you need to run a `go mod tidy`?

**Comment by srstack** [comment]
> unit-test reports: "Files go.sum and /tmp/go.sum.before differ". Maybe you need to run a `go mod tidy`?

tks~

**Review by dveeden — APPROVED** [review]

**Comment by dveeden** [comment]
Not sure why `unit-test` is still showing a failure. Running a `go mod tidy` locally gives a clean result.

**Pull request merged**
