### PR TITLE
dm: redirect stdout to log files

### PR DESCRIPTION
**Pull request by csuzhangxc**
### What problem does this PR solve? 

save stdout as we did for stderr

### What is changed and how it works?

redirect stdout to log files

### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by csuzhangxc** [comment]
@july2993 PTAL

**Review by july2993 — APPROVED** [review]

**Comment by july2993** [comment]
@csuzhangxc  pls resolve conflicts

**Comment by csuzhangxc** [comment]
@july2993 PTAL again

**Review by july2993 — APPROVED** [review]
/merge

**Pull request merged**
