### PR TITLE
dm: support monitored config

### LINKED ISSUE #1233: tiup dm not support deploy “monitored”
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

2. What did you expect to see?

yaml 

```
monitored:   // line: 7
  node_exporter_port: 39100
  blackbox_exporter_port: 39115
```

tiup dm deploy xx.yaml

```
Error: Failed to parse topology file bigdm.yaml (topology.parse_failed)
  caused by: yaml: unmarshal errors:
  line 7: field monitored not found in type spec.topology
```

**TiDB & DM is not on the same host ，Unable to view DM host resource usage。**

4. What version of TiUP are you using (`tiup --version`)?

```
v1.3.2 tiup
Go Version: go1.13
Git Branch: release-1.3
GitHash: 2d88460
```

### PR DESCRIPTION
**Pull request by 9547**
### What problem does this PR solve? 

fix #1233 

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Review by AstroProfundis — APPROVED** [review]

**Comment by AstroProfundis** [comment]
The tests are failing, I think we could use `v2.0.1` for DM instead of nightly.

**Comment by 9547** [comment]
> The tests are failing, I think we could use `v2.0.1` for DM instead of nightly.

It seems that the DM version is not well bound to black_box and node_export, even `v2.0.1`

image

**Comment by lucklove** [comment]
> > The tests are failing, I think we could use `v2.0.1` for DM instead of nightly.
> 
> It seems that the DM version is not well bound to black_box and node_export, even `v2.0.1`
> 
> image

You should put node_expoter and black_expoter here: https://github.com/pingcap/tiup/blob/master/components/dm/spec/bindversion.go#L12

Like https://github.com/pingcap/tiup/blob/master/pkg/cluster/spec/bindversion.go#L23

So that tiup-dm can detect what's the correct xxx_expoter version (instead of use the cluster version)

**Comment by lucklove** [comment]
Should deal with https://github.com/pingcap/tiup/blob/master/embed/templates/config/prometheus.yml.tpl#L17

DM doesn't has `node.rules.yml`, `blacker.rules.yml` and `bypass.rules.yml` in released versions. So maybe we should only config these files in TiDB context.

```
{{- if .MonitoredServers}}{{if .PDAddrs}}
  - 'node.rules.yml'
  - 'blacker.rules.yml'
  - 'bypass.rules.yml'
{{end}}{{- end}}
```

**Comment by lucklove** [comment]
@buggithubs This requirement is strange, grafana dashboard for DM cluster doesn't has exporter panel at all.

**Comment by lucklove** [comment]
I'm sorry, 9547. I have confirmed that we don't have a grafana panel for node exporter in DM cluster yet. It may take a little time to design one.

At this time, it's better implement this as a hidden feature: If the user doesn't configure `monitored` field, we just keep the old behavior and don't deploy node exporter and blackbox exporter. To archive this, we should implments [MonitoredOptions](https://github.com/pingcap/tiup/blob/master/components/dm/spec/topology_dm.go#L89) as a pointer so that if the user doesn't specify it, it will be nil.

The advantage of this scheme is that, some users deploy DM cluster overlaps TiDB cluster, some the the machines are shared between DM and TiDB. If DM and TiDB both deploy monitors by default, there will be conflict and the user may not be aware of that. When the user destroy one of the cluster, another cluster's exporters are destroyed, too. When I make users configure DM monitors explicitly, they will think about what these config means.

**Comment by lucklove** [comment]
I try to implement this scheme but get into trouble, I'm not sure what happened at this time:

屏幕快照 2021-03-25 下午5 29 02

I use the default setting and the conflict detected. https://github.com/lucklove/tiup/commit/36a5b3b390224ab1d45536fd3042f937fbef9815

**Comment by 9547** [comment]
> I try to implement this scheme but get into trouble, I'm not sure what happened at this time:
> 
> 屏幕快照 2021-03-25 下午5 29 02
> 
> I use the default setting and the conflict detected. [lucklove@36a5b3b](https://github.com/lucklove/tiup/commit/36a5b3b390224ab1d45536fd3042f937fbef9815)

I've cherry-picked your commit, why the conflict detected is the default config not updated. The root cause is this line https://github.com/lucklove/tiup/blob/36a5b3b390224ab1d45536fd3042f937fbef9815/components/dm/spec/topology_dm.go#L38

```go
	monitorOptionTypeName = reflect.TypeOf(&MonitoredOptions{}).Name()
```

the ponitor's reflact-type name is empty, so all the fields will be skipped in this line https://github.com/lucklove/tiup/blob/36a5b3b390224ab1d45536fd3042f937fbef9815/components/dm/spec/topology_dm.go#L697

**Pull request merged**
