### PR TITLE
cluster: when rolling restart PD, confirm that each peers can serve

### PR DESCRIPTION
**Pull request by HunDunDM**
Signed-off-by: Zheng Xiangsheng <hundundm@gmail.com>

### What problem does this PR solve? 

* When  `tiup reload pd` is executed, PD service may be unavailable for about 10 seconds.
  * If the PD immediately becomes the target of the transfer leader when it is just started, the [publish operation](https://github.com/etcd-io/etcd/blob/v3.4.3/etcdserver/server.go#L731) of the ETCD in the PD will block until it times out after 10 seconds, causing the PD Leader to be unavailable for a short time.

### What is changed and how it works?

* When rolling restart PD, confirm that each peers can serve after starting

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
   - sysbench
   - `tiup reload pd`

Related changes

 - Need to cherry-pick to the release branch

Release notes:

```release-note
Fix: wait the restarted PD instance to be healthy before stopping next one during rolling restart of PD nodes.
```

### CODE REVIEW

**Comment by King-Dylan** [comment]
The test results appear to be valid（affect about 1~2s）：
[ 575s ] thds: 16 tps: 6177.44 qps: 6177.44 (r/w/o: 0.00/6177.44/0.00) lat (ms,95%): 3.96 err/s: 0.00 reconn/s: 0.00
[ 576s ] thds: 16 tps: 6429.72 qps: 6429.72 (r/w/o: 0.00/6429.72/0.00) lat (ms,95%): 3.25 err/s: 0.00 reconn/s: 0.00
[ 577s ] thds: 16 tps: 6286.55 qps: 6286.55 (r/w/o: 0.00/6286.55/0.00) lat (ms,95%): 3.55 err/s: 0.00 reconn/s: 0.00
[ 578s ] thds: 16 tps: 6504.44 qps: 6504.44 (r/w/o: 0.00/6504.44/0.00) lat (ms,95%): 3.19 err/s: 0.00 reconn/s: 0.00
[ 579s ] thds: 16 tps: 6643.56 qps: 6643.56 (r/w/o: 0.00/6643.56/0.00) lat (ms,95%): 3.02 err/s: 0.00 reconn/s: 0.00
#### [ 580s ] thds: 16 tps: 3950.13 qps: 3950.13 (r/w/o: 0.00/3950.13/0.00) lat (ms,95%): 3.36 err/s: 0.00 reconn/s: 0.00
#### [ 581s ] thds: 16 tps: 655.29 qps: 655.29 (r/w/o: 0.00/655.29/0.00) lat (ms,95%): 4.25 err/s: 0.00 reconn/s: 0.00
[ 582s ] thds: 16 tps: 4388.59 qps: 4388.59 (r/w/o: 0.00/4388.59/0.00) lat (ms,95%): 3.07 err/s: 0.00 reconn/s: 0.00
[ 583s ] thds: 16 tps: 5389.28 qps: 5389.28 (r/w/o: 0.00/5389.28/0.00) lat (ms,95%): 3.68 err/s: 0.00 reconn/s: 0.00
[ 584s ] thds: 16 tps: 6331.06 qps: 6331.06 (r/w/o: 0.00/6331.06/0.00) lat (ms,95%): 3.55 err/s: 0.00 reconn/s: 0.00
[ 585s ] thds: 16 tps: 6439.14 qps: 6439.14 (r/w/o: 0.00/6439.14/0.00) lat (ms,95%): 3.62 err/s: 0.00 reconn/s: 0.00

**Comment by HunDunDM** [comment]
> The test results appear to be valid（affect about 1~2s）：

Thanks!

**Review by AstroProfundis — APPROVED** [review]

**Pull request merged**
