### PR TITLE
Revert "Fix tiflash not start with newest nightly PD (#902)"

### LINKED ISSUE #888: TiUP doesn't download tiflash component in `playground` subcommand and reports 'queer' error message.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

* `tiup playground nightly` or
* `tiup playground nightly --pd 1 --db 1 --kv 1 --tiflash 1`

However, this issue won't occur while I specify a version to these components.

2. What did you expect to see?

Create a local TiDB cluster normally.

3. What did you see instead?

```sh
🕙 14:30:57 ❯ tiup playground nightly
Starting component `playground`: /home/iosmanthus/.tiup/components/playground/v1.2.3/tiup-playground nightly
Playground Bootstrapping...
Start pd instance
Start tikv instance
Start tidb instance
Waiting for tidb 127.0.0.1:4000 ready  ... ⠏ 
Waiting for tidb 127.0.0.1:4000 ready  ... Done
Waiting for tikv 127.0.0.1:20160 ready  ... Done
Start tiflash instance
TiFlash failed to start: error requesting http://127.0.0.1:2379/pd/api/v1/config/replicate, response: "cannot update MaxReplicas when placement rules feature is enabled, please update rule instead"
, code 500
CLUSTER START SUCCESSFULLY, Enjoy it ^-^
To connect TiDB: mysql --host 127.0.0.1 --port 4000 -u root
To view the dashboard: http://127.0.0.1:2379/dashboard
To view the Prometheus: http://127.0.0.1:45943
To view the Grafana: http://127.0.0.1:3000
```

4. What version of TiUP are you using (`tiup --version`)?

```
v1.2.3 tiup
Go Version: go1.13
Git Branch: release-1.2
GitHash: df7e28a
```

### PR DESCRIPTION
**Pull request by lucklove**
This reverts commit 402079dbc40bc7397d4b136eccacee833c81d898.

We should reverts #902 because it introduced an issue:
https://github.com/pingcap/tiup/issues/1279

BTW, PD itself fixes #888 in https://github.com/tikv/pd/pull/3163
So we don't need #902 anymore with recently released PD.

However, after revert #902, ***TiFlash with old PD (before #3163) may not work with tiup-playground***

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by AstroProfundis** [comment]
https://github.com/tikv/pd/pull/3163 only appears on `v5.0.0-rc`, `v5.0.0-nightly` and  `master` of PD, so none of `v4.x` versions have that fix applied. I think we need to add version check instead of revert it back.

**Comment by lucklove** [comment]
@AstroProfundis It works!! PTAL

**Review by AstroProfundis — APPROVED** [review]

**Comment by lucklove** [comment]
I have test `tiup playground v4.0.{9, 10, 11, 12}`, all works fine.

**Pull request merged**
