### PR TITLE
Extract check cmd to pkg

### PR DESCRIPTION
**Pull request by baurine**
### What problem does this PR solve? 

Similar to PR #1139 , this PR is used to support PR #1172 (tiup web UI), so we can show the check result in the web UI without parsing the command line output.

WeCom20210316-174455@2x

### What is changed and how it works?

Extract the tiup cluster check interface to the pkg

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change

Side effects

 - Increased code complexity

Related changes

 - Need to cherry-pick to the release branch

Release notes:

```release-note
NONE
```

---
Manual test:

Output by this PR:

```
> bin/tiup-cluster check multi-host --cluster
+ Download necessary tools
  - Downloading check tools for linux/amd64 ... Done
+ Collect basic system information
+ Collect basic system information
+ Collect basic system information
+ Collect basic system information
+ Collect basic system information
  - Getting system info of 10.0.1.24:22 ... Done
  - Getting system info of 10.0.1.21:22 ... Done
  - Getting system info of 10.0.1.22:22 ... Done
  - Getting system info of 10.0.1.23:22 ... Done
+ Check system requirements
+ Check system requirements
  - Checking node 10.0.1.24 ... ⠼ Shell: host=10.0.1.24, sudo=false, command=`ss -lnt`
+ Check system requirements
+ Check system requirements
+ Check system requirements
+ Check system requirements
+ Check system requirements
+ Check system requirements
+ Check system requirements
+ Check system requirements
+ Check system requirements
+ Check system requirements
  - Checking node 10.0.1.24 ... Done
  - Checking node 10.0.1.21 ... Done
  - Checking node 10.0.1.22 ... Done
  - Checking node 10.0.1.23 ... Done
  - Checking node 10.0.1.22 ... Done
  - Checking node 10.0.1.21 ... Done
  - Checking node 10.0.1.22 ... Done
  - Checking node 10.0.1.23 ... Done
  - Checking node 10.0.1.21 ... Done
  - Checking node 10.0.1.21 ... Done
  - Checking node 10.0.1.21 ... Done
+ Cleanup check files
  - Cleanup check files on 10.0.1.24:22 ... Done
  - Cleanup check files on 10.0.1.21:22 ... Done
  - Cleanup check files on 10.0.1.22:22 ... Done
  - Cleanup check files on 10.0.1.23:22 ... Done
  - Cleanup check files on 10.0.1.22:22 ... Done
  - Cleanup check files on 10.0.1.21:22 ... Done
  - Cleanup check files on 10.0.1.22:22 ... Done
  - Cleanup check files on 10.0.1.23:22 ... Done
  - Cleanup check files on 10.0.1.21:22 ... Done
  - Cleanup check files on 10.0.1.21:22 ... Done
  - Cleanup check files on 10.0.1.21:22 ... Done
Node       Check           Result  Message
----       -----           ------  -------
10.0.1.22  permission      Pass    /home/tidb/tidb-deploy/tidb-4000 is writable
10.0.1.22  permission      Pass    /home/tidb/tidb-deploy/pd-2379 is writable
10.0.1.22  permission      Pass    /home/tidb/tidb-deploy/tikv-20160 is writable
10.0.1.22  permission      Pass    /home/tidb/tidb-deploy/tikv-20160/tidb-data is writable
10.0.1.22  permission      Pass    /home/tidb/tidb-deploy/pd-2379/tidb-data is writable
10.0.1.22  os-version      Pass    OS is Ubuntu 18.04.3 LTS 18.04.3
10.0.1.22  cpu-cores       Pass    number of CPU cores / threads: 1
10.0.1.22  swap            Fail    swap is enabled, please disable it for best performance
10.0.1.22  memory          Pass    memory size is 0MB
10.0.1.22  network         Fail    network speed of eth0 is 1000MB too low, needs 1GB or more
10.0.1.22  network         Fail    network speed of eth1 is 1000MB too low, needs 1GB or more
10.0.1.22  disk            Fail    mount point / does not have 'nodelalloc' option set
...
```

Output by code in origin/master:

```
> bin/tiup-cluster check multi-host --cluster
+ Download necessary tools
  - Downloading check tools for linux/amd64 ... Done
+ Collect basic system information
+ Collect basic system information
  - Getting system info of 10.0.1.24:22 ... ⠋ CopyComponent: component=insight, version=, remote=10.0.1.24:/tmp/tiup os=linux, arch=amd64
+ Collect basic system information
+ Collect basic system information
  - Getting system info of 10.0.1.24:22 ... Done
  - Getting system info of 10.0.1.21:22 ... Done
  - Getting system info of 10.0.1.22:22 ... Done
  - Getting system info of 10.0.1.23:22 ... Done
+ Check system requirements
+ Check system requirements
+ Check system requirements
+ Check system requirements
+ Check system requirements
+ Check system requirements
  - Checking node 10.0.1.24 ... ⠋ Shell: host=10.0.1.24, sudo=true, command=`sysctl -a`
+ Check system requirements
+ Check system requirements
+ Check system requirements
+ Check system requirements
+ Check system requirements
+ Check system requirements
  - Checking node 10.0.1.24 ... Done
  - Checking node 10.0.1.21 ... Done
  - Checking node 10.0.1.22 ... Done
  - Checking node 10.0.1.23 ... Done
  - Checking node 10.0.1.22 ... Done
  - Checking node 10.0.1.21 ... Done
  - Checking node 10.0.1.22 ... Done
  - Checking node 10.0.1.23 ... Done
  - Checking node 10.0.1.21 ... Done
  - Checking node 10.0.1.21 ... Done
  - Checking node 10.0.1.21 ... Done
+ Cleanup check files
  - Cleanup check files on 10.0.1.24:22 ... Done
  - Cleanup check files on 10.0.1.21:22 ... Done
  - Cleanup check files on 10.0.1.22:22 ... Done
  - Cleanup check files on 10.0.1.23:22 ... Done
  - Cleanup check files on 10.0.1.22:22 ... Done
  - Cleanup check files on 10.0.1.21:22 ... Done
  - Cleanup check files on 10.0.1.22:22 ... Done
  - Cleanup check files on 10.0.1.23:22 ... Done
  - Cleanup check files on 10.0.1.21:22 ... Done
  - Cleanup check files on 10.0.1.21:22 ... Done
  - Cleanup check files on 10.0.1.21:22 ... Done
Node       Check           Result  Message
----       -----           ------  -------
10.0.1.24  permission      Pass    /home/tidb/tidb-deploy/tiflash-9000 is writable
10.0.1.24  permission      Pass    /home/tidb/tidb-deploy/tiflash-9000/tidb-data is writable
10.0.1.24  os-version      Pass    OS is Ubuntu 18.04.3 LTS 18.04.3
10.0.1.24  cpu-cores       Pass    number of CPU cores / threads: 1
10.0.1.24  swap            Fail    swap is enabled, please disable it for best performance
10.0.1.24  memory          Pass    memory size is 0MB
10.0.1.24  network         Fail    network speed of eth0 is 1000MB too low, needs 1GB or more
10.0.1.24  network         Fail    network speed of eth1 is 1000MB too low, needs 1GB or more
10.0.1.24  disk            Fail    mount point / does not have 'nodelalloc' option set
10.0.1.24  disk            Warn    mount point / does not have 'noatime' option set
10.0.1.24  listening-port  Fail    port 8123 is already in use
10.0.1.24  listening-port  Fail    port 3930 is already in use
10.0.1.24  listening-port  Fail    port 20170 is already in use
10.0.1.24  listening-port  Fail    port 20292 is already in use
10.0.1.24  listening-port  Fail    port 8234 is already in use
10.0.1.24  listening-port  Fail    port 9000 is already in use
...
```

They are not exactly the same line by line, but the final result are the same.

### CODE REVIEW

**Review by AstroProfundis — APPROVED** [review]

**Comment by AstroProfundis** [comment]
> network speed of eth0 is 1000MB too low, needs 1GB or more

This output is not as expected, could you also change the `pkg/cluster/operation/check.go` file at near line 247 to use `>=` instead of `>`?

**Comment by baurine** [comment]
> > network speed of eth0 is 1000MB too low, needs 1GB or more
> 
> This output is not as expected, could you also change the `pkg/cluster/operation/check.go` file at near line 247 to use `>=` instead of `>`?

sure! will do it soon.

**Comment by baurine** [comment]
done!

image

**Pull request merged**
