### PR TITLE
playground: Enable AutoTLS by default

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve? 

TiDB Playground doesn't enable TLS by default. While TLS isn't needed in most cases to make the playground secure, it can help to detect issues with client code early on that could cause problems later when deployed on TiDB Cloud Serverless (which requires TLS).

### What is changed and how it works?

if there is no config specified, create a temporary config that enables
AutoTLS.

https://docs.pingcap.com/tidb/stable/tidb-configuration-file#auto-tls

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Code changes

 - Has exported variable/fields change

Side effects

 - Possible performance regression
 - Increased code complexity

Related changes

 - Need to update the documentation

Release notes:

```release-note
TiUP Playground enables AutoTLS by default
```

### CODE REVIEW

**Comment by dveeden** [comment]
@nexustar 

1. Is this ok or should we try to not set the config for versions that don't support autoTLS?
2. Should we put the config in `~/tiup/data/<name>/tidb-0/tidb.toml`  or is `/tmp/tidb-playground-config<random>` ok?

**Comment by dveeden** [comment]
@nexustar PTAL

**Review by kaaaaaaang — APPROVED** [review]
works fine with tidb v4.0.0 and v6.1.0

**Review by nexustar — APPROVED** [review]

**Review by kaaaaaaang — APPROVED** [review]

**Comment by kaaaaaaang** [comment]
some dev are using playground as a daily-develop tool and using it in ci. maybe it is is suitable to eable it by default

**Pull request merged**
