### PR TITLE
[DNM] TiUP Cluster UI (new)

### PR DESCRIPTION
**Pull request by baurine**
### What problem does this PR solve? 

Supply a web UI of tiup cluster component for users to easily deploy and operate a cluster.

Replace the old PR #706 , the old PR has too many conflicts with the latest master branch because the upstream changed too much.

### What is changed and how it works?

Add a web UI that includes both backend and frontend.

Compile it by:

```
$ make embed_cluster_ui
$ UI=1 make
```

Run it by:

```
$ bin/tiup-cluster --ui
```

Access `http://ip:8080` in the browser.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Code changes

 - Has exported function/method change
 - Has exported variable/fields change

Side effects

 - Increased code complexity

Related changes

 - Need to update the documentation

Release notes:

```release-note
- Supply a web UI of tiup cluster component for user to easily deploy and operate a cluster.
```

### CODE REVIEW

**Comment by baurine** [comment]
Some features have broken, still fixing them.

**Comment by baurine** [comment]
support show audit list in the web UI:

image

**Comment by baurine** [comment]
current support backup the cluster periodically:

WX20210326-154237@2x
WX20210326-155002@2x

**Comment by baurine** [comment]
支持降级：

image

WeCom20210330-114627@2x

**Comment by kaaaaaaang** [comment]
https://github.com/pingcap/tiunimanager

**Comment by baurine** [comment]
This PR can be closed because it's replaced by https://github.com/pingcap/tiunimanager

**Pull request closed without merging**
