### PR TITLE
Implement the errors metadata file generator

### PR DESCRIPTION
**Pull request by lonng**
### What problem does this PR solve? 

The RFC https://github.com/pingcap/tidb/blob/master/docs/design/2020-05-08-standardize-error-codes-and-messages.md proposes all components related to the TiDB ecosystem should use the normalized error code to. This PR implement the metadata generator.

### What is changed and how it works?

1. Add a new `errdoc-gen` generator to generate a script.
2. The generated script by `errdoc-gen` is used to generate the real `errors.toml`.

Usage:
```
# eg: ./errdoc-gen --source devel/pingap/tidb --module github.com/pingcap/tidb --output devel/pingap/tidb/errors.toml
./errdoc-gen --source /path/to/source/code --module ${module-name} --output /path/to/errors.toml
```

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by july2993** [comment]
Screen Shot 2020-10-20 at 11 35 41 AM

just try to use without reviewing PR, seem nothing generated?

**Comment by lonng** [comment]
@july2993 The path will relate to the source directory. The `errors.toml` will be placed at `/path/to/tidb/errors.toml`

**Comment by july2993** [comment]
just a header with nothing flowing
```
AUTOGENERATED BY github.com/pingcap/tiup/components/errdoc/errdoc-gen
DO NOT EDIT THIS FILE, PLEASE CHANGE ERROR DEFINITION IF CONTENT IMPROPER.

```

**Comment by lonng** [comment]
@july2993 Seems it caused by the symbol link. Fixed in b2c1045

**Comment by july2993** [comment]
Screen Shot 2020-10-20 at 1 59 28 PM

**Comment by lonng** [comment]
@july2993 Seems there are some invalid syntax source files.

**Review by july2993 — APPROVED** [review]

**Pull request merged**
