### PR TITLE
Add advertise addr for TiKV and PD

### PR DESCRIPTION
**Pull request by lucklove**
### What problem does this PR solve? 
Fix https://github.com/pingcap/tiup/issues/1218

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by lucklove** [comment]
This is a hidden feature, no release not and user document will be provided.

**Comment by 9547** [comment]
Also need to add `WithXXXAddr` in pd's `ScaleConfig` https://github.com/pingcap/tiup/pull/1224/files?file-filters%5B%5D=.go#diff-52ed75eb339663407c56ff6cf1b6bdf3a0995e7e9da391e4d28f113c9f14eb39R260-R270

**Comment by lucklove** [comment]
> Also need to add `WithXXXAddr` in pd's `ScaleConfig` https://github.com/pingcap/tiup/pull/1224/files?file-filters%5B%5D=.go#diff-52ed75eb339663407c56ff6cf1b6bdf3a0995e7e9da391e4d28f113c9f14eb39R260-R270

Oh, true

**Comment by AstroProfundis** [comment]
Do we need to also implement custom default values for these fields in `spec`? Or just leaving them empty is enough?

**Comment by 9547** [comment]
> Do we need to also implement custom default values for these fields in `spec`? Or just leaving them empty is enough?
 
Seems it's hard to set the default value which is based on other field in the `spec`, the `advertise-xxx` address are based on the `host` and `port`(the other fields). 

But we can always set a default value when the `pkg/cluster/template/scripts.NewXXXScript` is first invoked.

**Comment by AstroProfundis** [comment]
> based on other field in the `spec`

Actually we do have such logic as in https://github.com/pingcap/tiup/blob/197a8a3a0c0cab28116c1a122aa53d268d77b98f/pkg/cluster/spec/spec.go#L500

And yes that's complex so not necessarily a must, I'm wondering if it's possible for the filed to be uninitialized if we don't set it a default value during unmarshalling.

**Comment by lucklove** [comment]
> Do we need to also implement custom default values for these fields in `spec`? Or just leaving them empty is enough?

It's not a good idea to fill these fields with default value when it's empty, because it's a hidden feature and we don't wish users change it.

**Comment by AstroProfundis** [comment]
That sounds reasonable to me.

**Review by AstroProfundis — APPROVED** [review]

**Pull request merged**
