### PR TITLE
Fix tiflash start script

### PR DESCRIPTION
**Pull request by lucklove**
Fix https://github.com/pingcap/tiup/issues/642

### CODE REVIEW

**Review by 9547 — APPROVED** [review]
BTW, `>> log/tiflash_stderr.log` will only append the stderr log into file, but issue #642 seems to say the `tiflash/logs` not created?

**Comment by lucklove** [comment]
> BTW, `>> log/tiflash_stderr.log` will only append the stderr log into file, but issue #642 seems to say the `tiflash/logs` not created?

Good question. The log directory is empty is because the tiflash didn't start at all (it should be start by numactl but there is no numactl found), so there is no opportunity for it to create a log file.

**Comment by 9547** [comment]
> > BTW, `>> log/tiflash_stderr.log` will only append the stderr log into file, but issue #642 seems to say the `tiflash/logs` not created?
> 
> Good question. The log directory is empty is because the tiflash didn't start at all (it should be start by numactl but there is no numactl found), so there is no opportunity for it to create a log file.

I got it. I previously thought that issue want to say the log dir is missing, not the log files under log dir is missing :bear:

**Comment by glkappe** [comment]
> > BTW, `>> log/tiflash_stderr.log` will only append the stderr log into file, but issue #642 seems to say the `tiflash/logs` not created?
> 
> Good question. The log directory is empty is because the tiflash didn't start at all (it should be start by numactl but there is no numactl found), so there is no opportunity for it to create a log file.

So in files changed, does the final execution of the command change?
Newly added command line parameter `2>> "{{.LogDir}}/tiflash_stderr.log`, the output content should be printed in cmd.
So we can still locate the cause of the tiflash startup failure before `v1.3.0` ?

**Comment by 9547** [comment]
this behavior is the same as other components, we use systemctl to start/stop those components, if start failed,the error message was omited, and you can check the error log for more detail.

**Pull request merged**
