### PR TITLE
feat(cluster/spec): check alertmanager,prometheus's config

### PR DESCRIPTION
**Pull request by 9547**
### What problem does this PR solve? 
Check Alertmanager,Prometheus' config after `InitConfig`, should be merged after #1073 

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by lucklove** [comment]
It seems the config check failed

**Comment by 9547** [comment]
Hi @lucklove Is there any documents about the usage of the Ti Robot, such as I want to merge PR #A after #B...

**Comment by lucklove** [comment]
> Hi @lucklove Is there any documents about the usage of the Ti Robot, such as I want to merge PR #A after #B...

https://book.prow.tidb.io/#/

Here is all the commands, I think.

**Pull request merged**
