### PR TITLE
add default description

### PR DESCRIPTION
**Pull request by wangbinhe3db**
### What problem does this PR solve? 
when  tuip deploy
image
deafult  choice is N, but  here is no default description

### What is changed and how it works?
Attention:
    1. If the topology is not what you expected, check your yaml file.
    2. Please confirm there is no port/directory conflicts in same host.
Do you want to continue? [y/N]  (default=N):

have a  default description

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Review by birdstorm — APPROVED** [review]
LGTM

**Comment by AstroProfundis** [comment]
Ummm, the capital `N` in `[y/N]` is suggesting `N` is the default value...

If you would add a more expanded note about current default value, please add it in the `pkg/cliutil/tui.go` file.

**Comment by wangbinhe3db** [comment]
> Ummm, the capital `N` in `[y/N]` is suggesting `N` is the default value...
> 
> If you would add a more expanded note about current default value, please add it in the `pkg/cliutil/tui.go` file.

OK  I add it  in `pkg/cliutil/tui.go` file.

**Comment by AstroProfundis** [comment]
Thanks, that looks good to me. There is another func `PromptForConfirmYes()` as well, could you please modify that as well?

**Comment by AstroProfundis** [comment]
Ah, the description is not correct.

 - `PromptForConfirmNo()` wait for user to input a No and defaults to yes (if not matching No then assume yes)
 - `PromptForConfirmYes()` wait for user to input a Yes and defaults to no (if not matching Yes then assume no)

**Comment by wangbinhe3db** [comment]
> Ah, the description is not correct.
> 
> * `PromptForConfirmNo()` wait for user to input a No and defaults to yes (if not matching No then assume yes)
> * `PromptForConfirmYes()` wait for user to input a Yes and defaults to no (if not matching Yes then assume no)

en , my error , I will  PromptForConfirmNo in  other   pull request @AstroProfundis

**Review by 9547 — APPROVED** [review]

**Pull request merged**
