### PR TITLE
feat(node_exporter): add --collector.buddyinfo

### PR DESCRIPTION
**Pull request by 9547**
### What problem does this PR solve? 
implement #877 

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Review by lucklove — APPROVED** [review]
LGTM

**Comment by lucklove** [comment]
It seems that you changed the template file but forget to run `make pkger`. Please run `make pkger` and commit again.

**Comment by 9547** [comment]
Thanks for the advice, and i think maybe we can use tools like `pre-commit` to automatical run `make pkger` to generate the pkg if those template files changed, before commit

**Comment by lucklove** [comment]
> Thanks for the advice, and i think maybe we can use tools like `pre-commit` to automatical run `make pkger` to generate the pkg if those template files changed, before commit

That's a good ideal, but it seems git hook only works on local, do you know is there anyway to run it in github server?

**Comment by 9547** [comment]
Seems github didn't support git  hooks, the  only we can use is web hooks

**Comment by lucklove** [comment]
> Seems github didn't support git hooks, the only we can use is web hooks

Web hook can only do post-check, there is no need to add it since we have unit test to do it (and what I mean is that you should make pkger and push again to pass the unit test)

**Pull request merged**
