### PR TITLE
Tiny fix for the problem that the Drainer monitoring configuration of Prometheus is lost due to spelling.

### PR DESCRIPTION
**Pull request by SE-Bin**
Tiny fix for the problem that the Drainer monitoring configuration of Prometheus is lost due to spelling.

### What problem does this PR solve? 
Tiny fix for the problem that the Drainer monitoring configuration of Prometheus is lost due to spelling.

### What is changed and how it works?
Fix the spelling of "Drainer"

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Review by 9547 — APPROVED** [review]
/lgtm

**Comment by lucklove** [comment]
> /lgtm

It doesn't work if you left a comment `/lgtm` in `Files changed` tab, should left the comment in `Conversations` tab

**Comment by AstroProfundis** [comment]
@SE-Bin please sign the CLA so that we can merge the PR.

**Pull request merged**
