### PR TITLE
Update topology.example.yaml

### PR DESCRIPTION
**Pull request by yuzhibotao**
topology example with server_configs of tidb/pd/tikv

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by yuzhibotao** [comment]
topology example with server_configs of tidb/pd/tikv

**Comment by lonng** [comment]
@yuzhibotao Prefer to create a new file name `topology.config.example.yaml`.

**Review by AstroProfundis — COMMENTED** [review]
I think we can create a new file named `topology.example.full.yaml` or something like that to put all those configs

**Review by lucklove — APPROVED** [review]
awesome, LGTM

**Comment by lucklove** [comment]
> @yuzhibotao Prefer to create a new file name `topology.config.example.yaml`.

IMO, It's ok to keep this, because we have a [minimal.yaml](https://github.com/pingcap/tiup/blob/master/examples/minimal.yaml)

**Pull request merged**
