### PR TITLE
Playground: fix missing config file for tiflash

### PR DESCRIPTION
**Pull request by unbyte**
### What problem does this PR solve? 

When tiup playground starts tiflash, it outputs

image

It's because config file haven't been created, and this is because directory `/root/.tiup/data/SI4xAjv/tiflash-0/` haven't been created in this case .

### What is changed and how it works?

create the directory to store config file for tiflash before creating config file

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Related changes

 - Need to cherry-pick to the release branch

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Review by 9547 — APPROVED** [review]
/lgtm

**Comment by 9547** [comment]
Please add a new test case in [tests/tiup-playground/test_playground.sh](tests/tiup-playground/test_playground.sh), thank you. Maybe you can try to replace 0 with 1 and to see if the Github CI has enough memory to run TiFlash.

https://github.com/pingcap/tiup/blob/a290d33a1d9d4270bbfb67425ad2d45bdc3098d0/tests/tiup-playground/test_playground.sh#L53

**Comment by unbyte** [comment]
> Please add a new test case in [tests/tiup-playground/test_playground.sh](tests/tiup-playground/test_playground.sh), thank you. Maybe you can try to replace 0 with 1 and to see if the Github CI has enough memory to run TiFlash.

Thanks for your reminder

**Pull request merged**
