### PR TITLE
Add some desc when execute `tiup-cluster restart`

### PR DESCRIPTION
**Pull request by glkappe**
Add a warning description when the cluster restarts
Help understand the impact of restart,

### Check List 

Tests 

 - No code

Code changes

 - Has persistent data change

Side effects

Related changes

 - Need to cherry-pick to the release branch

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Review by AstroProfundis — APPROVED** [review]

**Comment by AstroProfundis** [comment]
It seems there are some issues with the image Github Actions uses, I'll wait until tomorrow to see if it could be fixed, otherwise we may need to update our CI jobs to use another image.

**Comment by glkappe** [comment]
Do i need to do something

**Comment by AstroProfundis** [comment]
Nope, I believe it's an issue on Github side, I'll try to find a way to workaround that.

**Pull request merged**
