### PR TITLE
feature: docker/up.sh with subnet

### PR DESCRIPTION
**Pull request by 9547**
### What problem does this PR solve? 

try to implement the #752 

### What is changed and how it works?

1. add `--subnet` in [docker/up.sh](docker/up.sh);
2. after the [docker/up.sh](docker/up.sh), it will generate an `TIUP_TEST_IP_PREFIX`(default to `172.19.0`) env in [docker/secret/control.env](docker/secret/control.env) 
3. in each e2e test case, we set the old `172.19.0` ip prefix to `$ipprefix` varialbe，which is equal to `TIUP_TEST_IP_PREFIX` and will be replaced with it before each test runs.

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Review by july2993 — COMMENTED** [review]
gooks good,
pls fix ci

**Review by AstroProfundis — APPROVED** [review]

**Comment by 9547** [comment]
Rebase from the master branch,  and can be merged right now.

> /merge

**Pull request merged**
