### PR TITLE
tests/tiup-cluster: check prometheus monitored components

### LINKED ISSUE #1038: tiup deployed prometheus can't generate alertmanager configurations correctly
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Use tiup cluster to deploy a tidb cluster and enable alertmanager.

2. What did you expect to see?
Alertmanger's configuration is generated in `prometheus.yaml`.

3. What did you see instead?
No alertmanger configuration is found.

4. What version of TiUP are you using (`tiup --version`)?
tiup version v1.3.1 tiup
Go Version: go1.13
Git Branch: release-1.3
GitHash: d51bd0c

### PR DESCRIPTION
**Pull request by 9547**
### What problem does this PR solve? 

fix #1038

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Review by AstroProfundis — APPROVED** [review]

**Comment by lucklove** [comment]
The test failed, there is something wrong, @9547 could you take a look?

**Comment by 9547** [comment]
> The test failed, there is something wrong, @9547 could you take a look?

I'll look at it tonight

**Pull request merged**
