### PR TITLE
clean: check process name before killing it

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve? 

The pid that is read from `tiup_process_meta` can be old and might be recycled due to pid wrap around or after restarts.

This PR checks if the `p.Name()` is `tiup-playground` before killing it.

```
Kill instance of `playground`, pid: 2804212
Clean instance of `playground`, directory: /home/dvaneeden/.tiup/data/crp
Process name mismatch (`/usr/bin/gjs` != `tiup-playground`, not killing it.
Clean instance of `playground`, directory: /home/dvaneeden/.tiup/data/crp
```

For a actual playground the data looks like this:
```
PROC cmdline: /home/dvaneeden/.tiup/components/playground/v1.11.3/tiup-playground -T crp --tiflash 0 --without-monitor v6.6.0
PROC cwd: /home/dvaneeden
PROC exe: /home/dvaneeden/.tiup/components/playground/v1.11.3/tiup-playground
PROC name: tiup-playground
```

For a different process (GNOME Weather) it looks like this:
```
PROC cmdline: /usr/bin/gjs /usr/share/org.gnome.Weather/org.gnome.Weather --gapplication-service
PROC cwd: /home/dvaneeden
PROC exe: /usr/bin/gjs-console
PROC name: /usr/bin/gjs
```

This is what https://godocs.io/github.com/shirou/gopsutil/v3/process shows for `p.Cmdline()`, `p.Cwd()`, `p.Exe()` and `p.Name()`.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Copying the `tiup_process_meta` and changing the process.

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by dveeden** [comment]
@nexustar any idea why "test_scale_tools_tls" fails? To me it doesn't look related to this PR.

**Comment by nexustar** [comment]
> @nexustar any idea why "test_scale_tools_tls" fails? To me it doesn't look related to this PR.

sadly, it is an unstable test, maybe due to small timeout

**Review by kaaaaaaang — APPROVED** [review]

**Pull request merged**
