### PR TITLE
Add Amazon Linux 2 as supported OS

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve? 

Mark Amazon Linux 2 as supported

- https://aws.amazon.com/blogs/startups/achieve-better-price-to-performance-for-tidb-graviton2-processors/
- https://aws.amazon.com/ec2/graviton/
- https://aws.amazon.com/amazon-linux-2/

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Release notes:
```release-note
Amazon Linux is no longer marked as unsupported
```

```
$ cat /etc/os-release 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

```
$ rpm -E %{rhel}
7
```

```
ip-**********.eu-central-1.compute.internal  os-version    Fail    os vendor amzn not supported
```

### CODE REVIEW

**Review by AstroProfundis — APPROVED** [review]

**Comment by yahonda** [comment]
Do we need to update https://docs.pingcap.com/tidb/stable/hardware-and-software-requirements to mention that 'Amazon Linux 2' is supported once the newer version of tiup released?

**Comment by dveeden** [comment]
> Do we need to update https://docs.pingcap.com/tidb/stable/hardware-and-software-requirements to mention that 'Amazon Linux 2' is supported once the newer version of tiup released?

Yes: https://github.com/pingcap/docs/pull/7473

**Comment by yahonda** [comment]
Thanks. I was not aware of that pull request.

**Pull request merged**
