### PR TITLE
mirror clone: Improve handling of latest versions

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve? 

When running `tiup mirror clone ... v5.0.0` it may download a different version of a component if there
is no v5.0.0 for that component. 

If you specify "v9999" it will cause `tiup mirror clone` to download the latest version of all components.

### What is changed and how it works?

1. Print a message when falling back on the latest version for a component
2. Allow the user to specify "latest" as version to get the latest version.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Try `tiup mirror clone /path/to/tiup-mirror --os linux --arch amd64 latest` and `tiup mirror clone /path/to/tiup-mirror --os linux --arch amd4 v5.0.0`.

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
Allow specifying "latest" as version for `tiup mirror clone`
```

### CODE REVIEW

**Comment by AstroProfundis** [comment]
I think it should be "latest" available version by default, so I'm not sure if it's necessary to add an alias to specify "latest". PTAL @lucklove

**Comment by dveeden** [comment]
> I think it should be "latest" available version by default, so I'm not sure if it's necessary to add an alias to specify "latest". PTAL @lucklove

Making "latest" the default would be ok with me as that is probably what people want if they don't specify `--full`. However that's not how it works now as you need to specify a version.

```
[dvaneeden@dve-carbon ~]$ tiup mirror clone ~/tiup-mirror/ --arch=amd64 --os=linux
Start to clone mirror, targetDir is /home/dvaneeden/tiup-mirror/, selectedVersions are []
If this does not meet expectations, please abort this process, read `tiup mirror clone --help` and run again
Arch [amd64]
OS [linux]
download https://tiup-mirrors.pingcap.com/tiup-linux-amd64.tar.gz 6.71 MiB / 6.71 MiB 100.00% 7.66 MiB p/s                                                                                    
[dvaneeden@dve-carbon ~]$ tiup mirror clone ~/tiup-mirror/ --arch=amd64 --os=linux v99
Start to clone mirror, targetDir is /home/dvaneeden/tiup-mirror/, selectedVersions are [v99]
If this does not meet expectations, please abort this process, read `tiup mirror clone --help` and run again
Arch [amd64]
OS [linux]
download https://tiup-mirrors.pingcap.com/alertmanager-v0.17.0-linux-amd64.tar.gz 22.54 MiB / 22.54 MiB 100.00% 15.71 MiB p/s                                                                 
download https://tiup-mirrors.pingcap.com/bench-v1.4.1-linux-amd64.tar.gz 7.84 MiB / 7.84 MiB 100.00% 8.94 MiB p/s                                                                            
download https://tiup-mirrors.pingcap.com/blackbox_exporter-v0.12.0-linux-amd64.tar.gz 4.72 MiB / 4.72 MiB 100.00% 6.12 MiB p/s                                                               
download https://tiup-mirrors.pingcap.com/br-v5.0.0-linux-amd64.tar.gz 41.08 MiB / 41.08 MiB 100.00% 23.98 MiB p/s                                                                            
download https://tiup-mirrors.pingcap.com/client-v1.4.1-linux-amd64.tar.gz 4.50 MiB / 4.50 MiB 100.00% 5.11 MiB p/s                                                                           
download https://tiup-mirrors.pingcap.com/cluster-v1.4.1-linux-amd64.tar.gz 8.05 MiB / 8.05 MiB 100.00% 187.73 MiB p/s                                                                        
download https://tiup-mirrors.pingcap.com/dm-v1.4.1-linux-amd64.tar.gz 7.73 MiB / 7.73 MiB 100.00% 69.69 MiB p/s                                                                              
download https://tiup-mirrors.pingcap.com/dm-master-v2.0.2-linux-amd64.tar.gz 1.19 MiB / 31.44 MiB 3.77% 1.92 MiB p/s                                                                         ^C
```

```
[dvaneeden@dve-carbon ~]$ tiup mirror clone ~/tiup-mirror/ --arch=amd64 --os=linux --tidb-lightning
Error: flag needs an argument: --tidb-lightning
[dvaneeden@dve-carbon ~]$ tiup mirror clone ~/tiup-mirror/ --arch=amd64 --os=linux --tidb-lightning=v999
Start to clone mirror, targetDir is /home/dvaneeden/tiup-mirror/, selectedVersions are []
If this does not meet expectations, please abort this process, read `tiup mirror clone --help` and run again
Arch [amd64]
OS [linux]
download https://tiup-mirrors.pingcap.com/tiup-linux-amd64.tar.gz 6.71 MiB / 6.71 MiB 100.00% 489.30 MiB p/s   
```

**Comment by AstroProfundis** [comment]
Oh I see, that's an issue of how `clone` parses the argument list.

**Comment by lucklove** [comment]
Clever implementation!!!

**Pull request merged**
