### PR TITLE
Support config on TiCDC

### PR DESCRIPTION
**Pull request by 9547**
### What problem does this PR solve? 
 implement #1205 

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by 9547** [comment]
@leoppro PTAL

**Review by lonng — COMMENTED** [review]
@lucklove PTAL

**Comment by csuzhangxc** [comment]
> Need to update the documentation

Is there any PR to update the documentation for this? @9547 @lucklove

**Comment by lucklove** [comment]
@csuzhangxc We have this all the time: https://docs.pingcap.com/zh/tidb/stable/tiup-cluster-topology-reference

Search CDC and cdc_servers

**Comment by csuzhangxc** [comment]
> @csuzhangxc We have this all the time: https://docs.pingcap.com/zh/tidb/stable/tiup-cluster-topology-reference
> 
> Search CDC and cdc_servers

not about `cdc_servers`. but some DBA/users don't know how to config `server_configs` for `cdc` like https://github.com/pingcap/tiup/issues/1205#issuecomment-805969321

**Comment by lucklove** [comment]
@csuzhangxc 
屏幕快照 2021-04-14 上午11 46 52

We have this in server_configs too. Just like any other components such as TiDB, TiKV .etc.

**Comment by csuzhangxc** [comment]
I know how to config, but some DBA/users do know. OK...

**Comment by lucklove** [comment]
> I know how to config, but some DBA/users do know. OK...

Then how to let them know... Because there is already documents just like other components....

**Comment by csuzhangxc** [comment]
> > I know how to config, but some DBA/users do know. OK...
> 
> Then how to let them know... Because there is already documents just like other components....

I shared the doc above with them, and explain it via IM again. 😹

**Pull request merged**
