### PR TITLE
cluster: upgrade tikv first then cdc

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve? 

Upgrade tikv first then cdc, to be compatible with v5.2.0 TiCDC.

### What is changed and how it works?

Change upgrade order.

### Check List 

 - Manual test (add detailed scripts or steps below)

```
# deploy and start cdc cluster v5.0.3
tiup cluster deploy cdc-cluster1 v5.0.3 top1.1kv.yml -y && tiup cluster start cdc-cluster1 -y
# upgrade cdc cluster to v5.2.0
./tiup-cluster upgrade cdc-cluster1 5.2.0 -y
...
+ [ Serial ] - UpgradeCluster
Upgrading component pd
        Restarting instance 172.16.5.33:47902
        Restart instance 172.16.5.33:47902 success
Upgrading component tikv
        Restarting instance 172.16.5.33:47906
        Restart instance 172.16.5.33:47906 success
Upgrading component tidb
        Restarting instance 172.16.5.33:47904
        Restart instance 172.16.5.33:47904 success
Upgrading component cdc
        Restarting instance 172.16.5.33:47913
        Restart instance 172.16.5.33:47913 success
Upgrading component prometheus
        Restarting instance 172.16.5.33:47908
        Restart instance 172.16.5.33:47908 success
Upgrading component grafana
        Restarting instance 172.16.5.33:47909
        Restart instance 172.16.5.33:47909 success
Upgrading component alertmanager
        Restarting instance 172.16.5.33:47910
        Restart instance 172.16.5.33:47910 success
Upgraded cluster `cdc-cluster1` successfully
```

Release notes:

```release-note
Fix TiCDC v5.2.0 upgrade failure.
```

### CODE REVIEW

**Comment by AstroProfundis** [comment]
Could you confirm the new order is safe for all other released TiDB versions?

**Comment by overvenus** [comment]
> Could you confirm the new order is safe for all other released TiDB versions?

I have tested following cases, they work fine:

* 4.0.6 -> 5.2.0
* 4.0.14 -> 5.2.0
* 5.0.3 -> 5.2.0
* 5.1.1 -> 5.2.0

**Review by lonng — APPROVED** [review]

**Pull request merged**
