### PR TITLE
typo(*): TiOps -> TiUp

### PR DESCRIPTION
**Pull request by 9547**
### What problem does this PR solve? 

s/TiOps/TiUP/g

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by unbyte** [comment]
image

it seems there are still a lot of typos

**Comment by AstroProfundis** [comment]
The `cluster` component was named as `tiops` before the initial GA release so...

**Comment by lucklove** [comment]
Can you use `TiUP` instead of `TiUp`? And some other places is still using `TiUp`, I think it should be `TiUP` because we have use it for a long time in the community....

**Comment by 9547** [comment]
> Can you use `TiUP` instead of `TiUp`? And some other places is still using `TiUp`, I think it should be `TiUP` because we have use it for a long time in the community....


1. tiops -> tiup
2. Ti[UuPp] -> TiUP

PTAL

**Pull request merged**
