### PR TITLE
add grafana embedding config

### PR DESCRIPTION
**Pull request by sunzhaoyang**
### What problem does this PR solve? 

There is no need for repeated  development work, it can be directly embedded grafana in WebUI to view Cluster statistics.

So it's need to make grafana allow anonymous access. 

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by ljun0712** [comment]
From a security point of view, do not use anonymous login to access the monitoring data of the cluster. Monitoring data is very important, and access to it requires permission management and logging.
A more secure way can be considered: provide username/password

**Comment by sunzhaoyang** [comment]
> From a security point of view, do not use anonymous login to access the monitoring data of the cluster. Monitoring data is very important, and access to it requires permission management and logging. A more secure way can be considered: provide username/password

Maybe we can tell users the risk and disable by default. Users could make the choice depend on the situation.

Security and convenience most of the time do not go hand in hand, we should let the user choose.

**Review by nexustar — APPROVED** [review]

**Pull request merged**
