### PR TITLE
fix the exit order of the components of playground

### PR DESCRIPTION
**Pull request by unbyte**
### What problem does this PR solve? 

#859 

### What is changed and how it works?

run components in new process groups so avoid an unexpected exit order

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Release notes:

```release-note
playground: consistent exit order of component processes
```

### CODE REVIEW

**Comment by unbyte** [comment]
image

**Review by AstroProfundis — APPROVED** [review]
LGTM

**Comment by lucklove** [comment]
@you06 PTAL

**Review by you06 — APPROVED** [review]
LGTM

**Pull request merged**
