### PR TITLE
pdms(playground, cluster): add name to start pdms

### PR DESCRIPTION
**Pull request by HuSharp**
### What problem does this PR solve? 
Ref [#8157](https://github.com/tikv/pd/pull/8157)

### What is changed and how it works?

after https://github.com/tikv/pd/pull/8157, we can start PDms with name.
But startup previous pd which support ms before 8.3.0 will failure because of `unkown flag`
img_v3_02cm_72c1d9cf-37ae-4b94-9399-ea4c42e450eg

for 8.2.0 
```bash
$ cat tidb-deploy/tso-3379/scripts/run_tso.sh
#!/bin/bash
set -e

# WARNING: This file was auto-generated. Do not edit!
#          All your edit might be overwritten!
DEPLOY_DIR=/root/husharp/tidb-deploy/tso-3379

cd "${DEPLOY_DIR}" || exit 1
exec env GODEBUG=madvdontneed=1 bin/pd-server services tso \
    --backend-endpoints="http://10.2.7.79:2379" \
    --listen-addr="http://10.2.7.79:3379" \
    --advertise-listen-addr="http://10.2.7.79:3379" \
    --config=conf/tso.toml \
    --log-file="/root/husharp/tidb-deploy/tso-3379/log/tso.log" 2>> "/root/husharp/tidb-deploy/tso-3379/log/tso_stderr.log"
```

after `./tiup-cluster upgrade tidb-test v8.2.0 --tso-version v8.3.0` and with 
```bash
tso_servers:
  - host:  10.2.7.79
    port: 3379
    name: "tso-0"
```

we can cat `tidb-deploy/tso-3379/scripts`

```bash
$ cat tidb-deploy/tso-3379/scripts/run_tso.sh
#!/bin/bash
set -e

# WARNING: This file was auto-generated. Do not edit!
#          All your edit might be overwritten!
DEPLOY_DIR=/root/husharp/tidb-deploy/tso-3379

cd "${DEPLOY_DIR}" || exit 1
exec env GODEBUG=madvdontneed=1 bin/pd-server services tso \
    --name="tso-0" \
    --backend-endpoints="http://10.2.7.79:2379" \
    --listen-addr="http://10.2.7.79:3379" \
    --advertise-listen-addr="http://10.2.7.79:3379" \
    --config=conf/tso.toml \
    --log-file="/root/husharp/tidb-deploy/tso-3379/log/tso.log" 2>> "/root/husharp/tidb-deploy/tso-3379/log/tso_stderr.log"

```

We need to keep compatible by changing pdms script

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by HuSharp** [comment]
PTAL, thx! @kaaaaaaang @rleungx

**Comment by HuSharp** [comment]
@kaaaaaaang @rleungx friendly ping :)

**Comment by HuSharp** [comment]
@xhebox can you take a look at this pr? thx~ :)

**Review by xhebox — APPROVED** [review]

**Pull request merged**
