### PR TITLE
cluster: fix wrong default initial-commit-ts in drainer

### LINKED ISSUE #1677: `--initial-commit-ts` is not assigned the correct default value
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

scale out drainer
```
drainer_servers: 
- host: 1055.1605.171.822
  ssh_port: 2123
  port: 82x9xx
  deploy_dir: /data/drainer-8212319/deploy
  data_dir: /data/drainer-8212319/data
  log_dir: /data/logs/drainer-8212319
  config: 
    syncer.db-type: mysql
    syncer.safe-mode: true
    syncer.to.host: 10123.112312334
    syncer.to.password: asdasd
    syncer.to.port: 3301239
    syncer.to.user: r123
    syncer.worker-count: 512
    syncer.txn-batch: 100
```

2. What did you expect to see?
cat run_drainer.sh

```
    --initial-commit-ts="-1" 2>> "/home/tidb/qh_new/deploy/drainer-3307/log/drainer_stderr.log"
```

3. What did you see instead?
    --initial-commit-ts="0" 2>> "/home/tidb/qh_new/deploy/drainer-3307/log/drainer_stderr.log"

4. What version of TiUP are you using (`tiup --version`)?
v1.8.0

### PR DESCRIPTION
**Pull request by nexustar**
### What problem does this PR solve? 

close #1677 #1680 

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by glkappe** [comment]
https://github.com/pingcap/tidb-binlog/blob/53a591e8258a97aefe9f5b705176e4a9d068c59e/arbiter/config.go#L66

In drainer's code, --initial-commit-ts may be of type int?

**Comment by nexustar** [comment]
> https://github.com/pingcap/tidb-binlog/blob/53a591e8258a97aefe9f5b705176e4a9d068c59e/arbiter/config.go#L66
> 
> In drainer's code, --initial-commit-ts may be of type int?

Type of DrainerSpec.CommitTS is only used inside tiup-cluster, it is the same after yaml.Marshal()
if it need to be int, we should modify template of run_drainer.sh

**Review by AstroProfundis — APPROVED** [review]

**Pull request merged**
