### PR TITLE
cluster: support init root password

### LINKED ISSUE #1660: Tiup set Root Password during deployment
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

Currently, TiDB will create a root user with no password and bind to 0.0.0.0/::. This is a potential security issue if users do not have a firewall configured correctly, or if a rogue actor has local access.
TiDB need support to set the password for root user.

**Why the featue is needed:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by AstroProfundis**
### What problem does this PR solve? 
Close #1660 

### What is changed and how it works?
An `--init` argument is added to `tiup-cluster start` subcommand, it generates a 18 chars long random password and set it to the `root@'%'` user.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Related changes

 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by nexustar** [comment]
Is it available for TLS-enabled cluster？

**Comment by AstroProfundis** [comment]
> Is it available for TLS-enabled cluster？

Yes, as we don't support TLS encrypted MySQL client yet, the protocol between client and TiDB server is identical with those TLS disabled.

**Comment by srstack** [comment]
> Is it available for TLS-enabled cluster？

TLS-enabled means to enable TLS encrypted communication between TiDB components, but does not include the communication between MySQL Client and TiDB.

**Review by srstack — APPROVED** [review]
/LGTM

**Review by nexustar — APPROVED** [review]

**Pull request merged**
