### PR TITLE
Turn off THP added to boot

### PR DESCRIPTION
**Pull request by WalterWj**
### What problem does this PR solve? 
Troubleshoot the problem that a large page of the server opens after the server restarts

### What is changed and how it works?
Start The large page is opened：
image

tiup check apply：
image

the config:
image

You can see that THP has been turned off, and the shutdown is written into the Open startup item

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Review by breezewish — APPROVED** [review]
LGTM

**Comment by kaaaaaaang** [comment]
I think the automatic modification of /etc/rc.local has too much intrusiveness and may not be suitable for all operating systems and customer environments.

**Comment by WalterWj** [comment]
> I think the automatic modification of /etc/rc.local has too much intrusiveness and may not be suitable for all operating systems and customer environments.

How about a judgment in the code? Do not modify this section if the rc.local file does not exist?

**Comment by kaaaaaaang** [comment]
https://github.com/pingcap/tiup/issues/2360

**Pull request closed without merging**
