### PR TITLE
enable but inact memory profiling

### LINKED ISSUE #1270: enable but deactive memory profiling for TiKV
## Feature Request

**Is your feature request related to a problem? Please describe:**

Memory profiling current can't work. PTAL https://github.com/tikv/tikv/issues/9538.

**Describe the feature you'd like:**

`export MALLOC_CONF=prof:true,prof_active:false` before starts TiKVs.
PTAL https://github.com/jemalloc/jemalloc/issues/2049.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

### What problem does this PR solve? 
Close #1270 and https://github.com/tikv/tikv/issues/9538.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
   1. Start a TiKV cluster with the environment variable set.
   2. wget "http://172.16.4.78:50013/debug/pprof/heap?seconds=1" to dump a memory profiling

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by lucklove** [comment]
To fix https://github.com/tikv/tikv/issues/9538, maybe you want to change `tiup-playground` instead of `tiup-cluster`?

**Comment by hicqu** [comment]
> To fix [tikv/tikv#9538](https://github.com/tikv/tikv/issues/9538), maybe you want to change `tiup-playground` instead of `tiup-cluster`?

@lucklove all TiKV clusters have the problem, regardless they are deployed with `playground` or `cluster`.

This PR is only for `cluster`, do you have any idea for setting environment variables for `playground`?

**Comment by hicqu** [comment]
BTW I will do a bench for this change. The result will be post later.

**Comment by lucklove** [comment]
> > To fix [tikv/tikv#9538](https://github.com/tikv/tikv/issues/9538), maybe you want to change `tiup-playground` instead of `tiup-cluster`?
> 
> @lucklove all TiKV clusters have the problem, regardless they are deployed with `playground` or `cluster`.
> 
> This PR is only for `cluster`, do you have any idea for setting environment variables for `playground`?

TiUP set envs for each component [here](https://github.com/pingcap/tiup/blob/master/pkg/exec/run.go#L224). 

1. You can add a `Envs []string` filed for [PrepareCommandParams](https://github.com/pingcap/tiup/blob/master/pkg/exec/run.go#L129) 
2. And add `envs = append(envs, p.Envs)` on L224.
3. Then add envs arg for [NewComponentProcess](https://github.com/pingcap/tiup/blob/master/components/playground/instance/process.go#L88)
4. Add your env when call [NewComponentProcess in TiKVInstance](https://github.com/pingcap/tiup/blob/master/components/playground/instance/tikv.go#L74)

**Comment by hicqu** [comment]
I have benchmarked it, here is the result:
```
without any environment variables:
$ cargo bench
running 7 tests
test bench_malloc_128k ... bench:          39 ns/iter (+/- 7)
test bench_malloc_128m ... bench:       4,134 ns/iter (+/- 412)
test bench_malloc_1g   ... bench:       8,478 ns/iter (+/- 2,356)
test bench_malloc_1k   ... bench:          48 ns/iter (+/- 5)
test bench_malloc_1m   ... bench:          37 ns/iter (+/- 5)
test bench_malloc_8k   ... bench:          30 ns/iter (+/- 4)
test bench_malloc_8m   ... bench:          35 ns/iter (+/- 3)
```
```
with `export MALLOC_CONF="prof:true,prof_active:true,prof.active:false"`
$ cargo bench
running 7 tests
test bench_malloc_128k ... bench:          37 ns/iter (+/- 16)
test bench_malloc_128m ... bench:       4,136 ns/iter (+/- 605)
test bench_malloc_1g   ... bench:       8,426 ns/iter (+/- 1,134)
test bench_malloc_1k   ... bench:          44 ns/iter (+/- 6)
test bench_malloc_1m   ... bench:          35 ns/iter (+/- 3)
test bench_malloc_8k   ... bench:          32 ns/iter (+/- 3)
test bench_malloc_8m   ... bench:          37 ns/iter (+/- 5)
```

There aren't obvious dirrerences.

The reason is memory profiling is compiled for both 2 cases, and it's not actived in both 2 cases.

**Pull request merged**
