### PR TITLE
fix: exporter and grafana are abnormal in prometheus

### LINKED ISSUE #1852: cluster:  enable tls, exporter and grafana are abnormal in prometheus
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

MhLrMzQL2h

image

2. What did you expect to see?

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?

### PR DESCRIPTION
**Pull request by srstack**
### What problem does this PR solve? 

close #1852 

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Review by nexustar — COMMENTED** [review]
instead of use tcp on all port probe, I think we had better use another job

**Comment by srstack** [comment]
> instead of use tcp on all port probe, I think we had better use another job

Using another job will involve some other configuration, which will become complicated.

**Comment by srstack** [comment]
> instead of use tcp on all port probe, I think we had better use another job

ok

**Comment by srstack** [comment]
> instead of use tcp on all port probe, I think we had better use another job

cc

**Review by nexustar — APPROVED** [review]

**Pull request merged**
