### PR TITLE
cluster:  completing the os type of the host

### PR DESCRIPTION
**Pull request by srstack**
### What problem does this PR solve? 

Previously, the host would use the global os by default, but if it is a multi os mixed deployment, an exception will occur.

### What is changed and how it works?

Completing the os type of the host  like full cpu architecture 

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by nexustar** [comment]
Will we support multi os mixed deployment?

**Comment by srstack** [comment]
> Will we support multi os mixed deployment?
just  for mac.   ：(

**Review by AstroProfundis — APPROVED** [review]

**Comment by AstroProfundis** [comment]
We don't support mixed OS in the cluster (the on-going macOS support will only be released with local deployment), but it's fine to make the code compatible with that, as long as our integrate tests on Linux pass.

**Pull request merged**
