### PR TITLE
cluster: fix stdout and stderr

### PR DESCRIPTION
**Pull request by tongtongyin**
### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Review by AstroProfundis — APPROVED** [review]

**Comment by AstroProfundis** [comment]
Seems the tests are keep failing, maybe something was depending on wrong stdout/stderr channel?

**Comment by nexustar** [comment]
GetOutputs has the same bug, you need to modify them together :(

**Comment by tongtongyin** [comment]
It has been updated. /cc @AstroProfundis

**Comment by tongtongyin** [comment]
> nexustar

It has been updated.

**Review by srstack — APPROVED** [review]

**Pull request merged**
