### PR TITLE
fix: tiup supports define root_url and enable anonymous in grafana.ini

### PR DESCRIPTION
**Pull request by mianhk**
### What problem does this PR solve? 
fix: #849 

### What is changed and how it works?
1. You can configure Grafana to run behind a reverse proxy.
   reference: https://grafana.com/tutorials/run-grafana-behind-a-proxy/#1
2. You can set grafana access anonymous

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
```
tiup cluster edit-config test_cluster

support config:
- host: 127.0.0.2
  ssh_port: 22
  arch: amd64
  os: linux
  username: admin
  password: admin
  anonymous_enable: true
  root_url: /tidb/grafana/test-cluster
  domain: example.com
```

 Then, you can get a grafana.ini like:
```
[auth.anonymous]
enabled = true
# The full public facing url
[server]
domain = example.com
...
root_url = /tidb/grafana/test-cluster
server_from_sub_path = true
```
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by lucklove** [comment]
In https://grafana.com/tutorials/run-grafana-behind-a-proxy/#1

It says:

```
When running Grafana behind a proxy, you need to configure the domain name to let Grafana know how to render links and redirects correctly.
```

And the final example is like:

```
[server]
domain = example.com
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
serve_from_sub_path = true
```

So I think maybe you forget to set the domain (by default, it's the IP address).

I suggest that you can add a `Domain` field and parse the domain from the root_url, if the root_url is not set, set `Domain` to the IP address.

**Comment by mianhk** [comment]
> In https://grafana.com/tutorials/run-grafana-behind-a-proxy/#1
> 
> It says:
> 
> ```
> When running Grafana behind a proxy, you need to configure the domain name to let Grafana know how to render links and redirects correctly.
> ```
> 
> And the final example is like:
> 
> ```
> [server]
> domain = example.com
> root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
> serve_from_sub_path = true
> ```
> 
> So I think maybe you forget to set the domain (by default, it's the IP address).
> 
> I suggest that you can add a `Domain` field and parse the domain from the root_url, if the root_url is not set, set `Domain` to the IP address.

OK,I add domain field parsed from domain if root_url is set or not cause someone may only set domain.

**Pull request merged**
