### PR TITLE
Fix typo with find command

### PR DESCRIPTION
**Pull request by rkazak**
Fix typo for find command.

### What problem does this PR solve? 

When running make we see

```
rkazak@rkazaknb tiup % make
gofmt (simplify)
goimports (if installed)
linting
./tools/check/check-lint.sh
find: illegal option -- n
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
go mod tidy
```

### What is changed and how it works?

Added in missing '.' - local dir path.

```
rkazak@rkazaknb tiup % make        
gofmt (simplify)
goimports (if installed)
linting
./tools/check/check-lint.sh
go mod tidy
```

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by lucklove** [comment]
Thank you @rkazak rkazak

**Review by AstroProfundis — APPROVED** [review]

**Pull request merged**
