### PR TITLE
Skip download nightly package when it exists

### PR DESCRIPTION
**Pull request by lucklove**
Fix https://github.com/pingcap/tiup/issues/565

Signed-off-by: lucklove <gnu.crazier@gmail.com>

### What problem does this PR solve? 
Fix https://github.com/pingcap/tiup/issues/565

### What is changed and how it works?
Stop ignoring nightly when check if we should download. This is ok because the `VerifyComponent` step will remove old nightly version.

### Check List 

Tests 
 - Manual test (add detailed scripts or steps below)

Related changes

 - Need to cherry-pick to the release branch

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Review by july2993 — COMMENTED** [review]
I think you can not skip, the nightly will be updated.
need to check the checksum for skip download

**Comment by lonng** [comment]
@lucklove Yes, as @july2993 said, you cannot skip the downloading for the nightly version even though the tarball exists.

**Comment by lucklove** [comment]
@july2993 @lonng Hey guys, pay attention on [this line](https://github.com/pingcap/tiup/blob/528dc6126f88322962e41cf043a2f96940a7368f/pkg/cluster/operation/download.go#L51), it will check if the tarball have correct checksum, if not, the tarball will be deleted. So if the nightly has been updated, the old one will be deleted and the condition `utils.IsNotExist(srcPath)` will be true and the newest nightly will be downloaded again.

**Review by lonng — APPROVED** [review]
LGTM

**Pull request merged**
