### PR TITLE
playground: fix cannot find nightly version

### PR DESCRIPTION
**Pull request by nexustar**
### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Review by AstroProfundis — APPROVED** [review]

**Comment by AstroProfundis** [comment]
We should also add a note on the "starting component" outputs to let users know which version of the component is actually running (as they may not with strictly the same version anymore)

**Comment by nexustar** [comment]
> We should also add a note on the "starting component" outputs to let users know which version of the component is actually running (as they may not with strictly the same version anymore)

this fix is for v1.8.x, I will prepare another PR for that

**Review by srstack — COMMENTED** [review]
LGTM

**Review by srstack — APPROVED** [review]

**Pull request merged**
