### PR TITLE
Add --cluster.advertise-address to  embed/templates/scripts/run_alertmanager.sh.tpl

### PR DESCRIPTION
**Pull request by luyomo**
### What problem does this PR solve? 
https://github.com/pingcap/tiup/issues/2155

### What is changed and how it works?
Add --cluster.advertise-address to alertmanger startup script. 
https://serverfault.com/questions/1024890/prometheus-alert-manager-error-component-cluster-err-couldnt-deduce-an-advert

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by luyomo** [comment]
/cc @reviewer
Please take a look.

**Comment by nexustar** [comment]
I guess what you need is advertise-host, not advertise-port?

**Comment by luyomo** [comment]
> I guess what you need is advertise-host, not advertise-port?
Yes. It needs advertise-host:advertise-port.  I assume that the advertise address is same to the listening host.

**Comment by nexustar** [comment]
> > I guess what you need is advertise-host, not advertise-port?
> > Yes. It needs advertise-host:advertise-port.  I assume that the advertise address is same to the listening host.

first, listening host may be 0.0.0.0. second, what's difference between advertise-port and web-port?

**Comment by nexustar** [comment]
I think it is enough to add `ClusterAdvertiseAddr: utils.JoinHostPort(i.GetHost(), spec.ClusterPort),`

**Pull request closed without merging**
