### PR TITLE
cluster: nightly version could not be compared

### PR DESCRIPTION
**Pull request by srstack**
### What problem does this PR solve? 

close https://github.com/pingcap/tiflow/issues/4149

### What is changed and how it works?

Get the complete nightly version number before initconfig operation 

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Code changes

Side effects

Related changes

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by srstack** [comment]
I'm not sure for the time being whether there is a comparison of nightly versions in other places.

**Review by AstroProfundis — APPROVED** [review]

**Comment by AstroProfundis** [comment]
/hold

wait for verification from reporter

**Comment by AstroProfundis** [comment]
/unhold

There is no response from reporter for few days, I'll merge this, if anything still not working we could fix that in another PR.

**Pull request merged**
