### PR TITLE
Add darwin-arm64 not support hint for install.sh

### PR DESCRIPTION
**Pull request by terasum**
The darwin-arm64 is not supported currently, and add some friendly hint.

### What problem does this PR solve? 

temporary fix for #1122 

### What is changed and how it works?

Add some hints 

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by lucklove** [comment]
Could you please modify [local_install.sh](https://github.com/pingcap/tiup/blob/master/pkg/cluster/template/install/local_install.sh.go#L46) too? This is used for offline  installation

**Comment by terasum** [comment]
@lucklove sure! I will fix local_install.sh too!

**Comment by terasum** [comment]
@lucklove Hi, please take a look again, thanks.

**Comment by baurine** [comment]
Will we support it and when? it seems some guys start to use M1.

**Comment by lucklove** [comment]
@baurine We need wait TiDB/TiKV/PD support that first, otherwise the user only have a bare TiUP

**Comment by baurine** [comment]
> @baurine We need wait TiDB/TiKV/PD support that first, otherwise the user only have a bare TiUP

make sense, now the TiKV can't run on M1.

**Pull request merged**
